const CONFIG = 'CONFIG';
const ADD_CURRENCY_EXCHANGE = 'ADD_CURRENCY_EXCHANGE';
const SAVE_CURRENT_EXCHANGE_RATES = 'SAVE_CURRENT_EXCHANGE_RATES';
const REMOVE_CURRENCY_EXCHANGE = 'REMOVE_CURRENCY_EXCHANGE';

const SAVE_CURRENCY_CONFIGURATION = 'SAVE_CURRENCY_CONFIGURATION';


//Actions and dispatchers
const GET_CURRENCY_CONFIGURATION_ACTION = 'GET_CURRENCY_CONFIGURATION_ACTION';
const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
const CHANGE_CURRENCY_ACTION = 'CHANGE_CURRENCY_ACTION';

//Sagas
const getExchangeCurrencyAction = 'CHANGE_CURRENCY_ACTION';
const getExchangeConfiguration = 'GET_EXCHANGE_CONFIGURATION';



export {
    CONFIG,
    SAVE_CURRENCY_CONFIGURATION,
    REMOVE_CURRENCY_EXCHANGE,
    SAVE_CURRENT_EXCHANGE_RATES,
    ADD_CURRENCY_EXCHANGE,
    GET_CURRENCY_CONFIGURATION_ACTION,
    CHANGE_CURRENCY, 
    CHANGE_CURRENCY_ACTION,
    getExchangeCurrencyAction,
    getExchangeConfiguration
 }